// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drdcgppydxrtvezvelzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZGNncHB5ZHhydHZlenZlbHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjA1MDcsImV4cCI6MjA3Mjc5NjUwN30.Srf2iM0Ci-zg7RQhdReux5bU1sI6bErR-bBDcVLvWLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});